#!/usr/bin/env python3
"""Embed the dependency-free UI as deterministic gzip in flash (no filesystem)."""
import argparse
import gzip
import hashlib
from pathlib import Path

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
html = (root / 'web/index.html').read_text()
html = html.replace('/* INLINE_CSS */', (root / 'web/app.css').read_text())
html = html.replace('/* INLINE_JS */', (root / 'web/app.js').read_text())
data = gzip.compress(html.encode(), compresslevel=9, mtime=0)
# Python 3.11/3.12 can delegate mtime=0 to zlib, which writes a platform-specific
# OS byte. Canonicalize it to "unknown" (255), as newer Python versions do.
data = data[:9] + b'\xff' + data[10:]
etag = hashlib.sha256(data).hexdigest()[:16]
lines = ['// Generated by tools/embed_web.py. Edit web/ sources, not this file.',
         '#pragma once', '#include <Arduino.h>',
         f'const char WEB_ETAG[] = "\\"{etag}\\"";',
         'const uint8_t WEB_PAGE[] PROGMEM = {']
lines += [','.join(f'0x{x:02x}' for x in data[i:i+24]) + ',' for i in range(0, len(data), 24)]
text = '\n'.join(lines + ['};', ''])
target = root / 'firmware/weather_clock/web_assets.h'
if args.check:
    if not target.exists() or target.read_text() != text:
        raise SystemExit('Web assets are stale: run python3 tools/embed_web.py')
else:
    target.write_text(text)
print(f'Web UI: {len(html.encode()):,} bytes, {len(data):,} bytes gzip in flash')
